apiVersion: v1
kind: Service 
metadata:
  name: fitness-backend-service
  namespace: ai-fitness-coach

spec:
  type: ClusterIP
  selector:
    app: fitness-backend
  ports:
  - port: 8000
    targetPort: 8000
