apiVersion: v1
kind: Service
metadata:
  name: fitness-frontend-service
  namespace: ai-fitness-coach

spec:
  type: LoadBalancer
  selector:
    app: fitness-frontend
  ports:
  - port: 80
    targetPort: 8501